### ISSUE TITLE
Please add a nickname column when adding a user to a server

### ISSUE THREAD

**Issue by johnlui** [shadowsocks/shadowsocks-manager#30]
Thanks for your awesome project!

I use it in my startup company to give everyone a single account, but  I need give every port-password a nickname to manage them easier now. Thanks very much!

**Comment by gyteng** [comment]
Did you mean users can login with email&password or nickname&password?
2016年7月8日 13:57，"John Lui" <notifications@github.com>写道：

Thanks for your awesome project!

I use it in my startup company to give everyone a single account, but I
need give every port-password a nickname to manage them easier now. Thanks
very much!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shadowsocks/shadowsocks-manager/issues/30>, or mute the
thread
<https://github.com/notifications/unsubscribe/ABdi0eFGepz_7vzXLG1ZM3eUHvKou5ORks5qTebegaJpZM4JHvpG>
.

**Comment by johnlui** [comment]
Not exactly, I mean when I add port-password on /admin/serverPage/***/addAccount page, if there is a nickname for this port-password may be more friendly.
